pipeline:
  build:
    image: skyevg/nix-godot-ci:latest
    commands:
      - mkdir build
      - godot --headless --export-release Web build/index.html
  upload:
    image: woodpeckerci/plugin-s3
    settings:
      bucket: tjt-builds
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: build/**/*
      target: /${CI_COMMIT_SHA}
      acl: public-read
      endpoint: https://s3.us-west-004.backblazeb2.com