pipeline:
  build:
    image: skyevg/nix-godot-ci:latest
    commands:
      - mkdir build
      - godot --headless --export-release Web build/index.html
  upload:
    image: woodpeckerci/plugin-s3
    settings:
      bucket: tjt-builds
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: build/**/*
      target: /${CI_COMMIT_SHA}
      acl: public-read
      endpoint: https://s3.us-west-004.backblazeb2.com
  notify:
    image: curlimages/curl
    commands:
      - 'curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"Job $CI_SYSTEM_LINK finished\nLink: https://tjt-ci.skyevg.systems/$CI_COMMIT_SHA/build/index.html\"}" $WEBHOOK_LINK'
    secrets:
      - webhook_link